// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Tk_MAJss06xgenXwBwhopV-Vj4ay-EA',
    appId: '1:591017225407:web:cc44bfad72ed31c981aa0a',
    messagingSenderId: '591017225407',
    projectId: 'dmart-3dd9e',
    authDomain: 'dmart-3dd9e.firebaseapp.com',
    storageBucket: 'dmart-3dd9e.appspot.com',
    measurementId: 'G-067T542MJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8gSMLw49AZ8CiQ1pn97T-Ke13wozE-PE',
    appId: '1:591017225407:android:6f9d07cbe7f6f61681aa0a',
    messagingSenderId: '591017225407',
    projectId: 'dmart-3dd9e',
    storageBucket: 'dmart-3dd9e.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1Tk_MAJss06xgenXwBwhopV-Vj4ay-EA',
    appId: '1:591017225407:web:449dc85ff28fb0b881aa0a',
    messagingSenderId: '591017225407',
    projectId: 'dmart-3dd9e',
    authDomain: 'dmart-3dd9e.firebaseapp.com',
    storageBucket: 'dmart-3dd9e.appspot.com',
    measurementId: 'G-XNR4592P0E',
  );
}
