const appname = "D-Mart",
    appversion = "Version 1.0.0",
    credits = "@ Dev's",
    email = "E-mail",
    email_hint = "admin@admin.com",
    pswd = "Password",
    repswd = "Re-enter your password",
    name = "Name",
    namehint = "Enter yor name",
    pswd_hint = "* * * * * * * *",
    forget_pswd = "forget password",
    login = "Log in",
    logout = "Log Out",
    loggedin = "Logged in successfully",
    loggedout = "Logged out successfully",
    sig_up = "Sign up",
    createnewacc = "or,create a new account",
    loginwith = "Log in with",
    alrdyacc = "already have an account? ",
    home = "Home",
    categories = "Categories",
    cart = "Cart",
    account = "Account",
    search = "Search anything",
    todaydeal = "Today's Deal",
    flashsale = "Flash s\Sale",
    topseller = "Top Seller",
    brands = "Brands",
    topcat = "Top Catogeries",
    featcat = " Featured Categories",
    womendrs = "Women Dress",
    girlwatch = "Girls watchs",
    mobfon = "Mobile Phones",
    boysglas = "Boys Glasses",
    girlsdrs = "Girls Dresses",
    featuredprod = "Featured Prodect",
    automob = "Automobile",
    kidstoy = "Kids & Toys",
    sports = "Sports",
    jwellry = "Jwellery",
    cellfon = "Cellphone & Tab",
    furniture = "Furniture",
    compu = "Computer & Accessories",
    mencloth = "Men Clothing & Fashion",
    video = "Video",
    reviews = "Reviews",
    sellerpolicy = "Selller Policy",
    returnpolicy = "Return Policy",
    supportpolicy = "Support Policy",
    productsyoulike = "Prodect you may like",
    tshirt = "T-Shirts";


//profile

const whishlist =  "My Wish list", orders = "My Orders", msg = "Messages",oldpass = "Old password",newpass = "New password";

const paypal = "Paypal",stripe = "Stripe", cod = "Cash On Delivery";
