const appname = "D-Mart";
const appversion = "Version 1.0.0";
const credits = "@ Dev's";
const email = "E-mail";
const email_hint = "admin@admin.com";
const pswd = "Password";
const repswd = "Re-enter your password";
const name = "Name";
const namehint = "Enter yor name";
const pswd_hint = "* * * * * * * *";
const forget_pswd = "forget password";
const login = "Log in";
const sig_up = "Sign up";
const createnewacc = "or,create a new account";
const loginwith = "Log in with";
const alrdyacc = "already have an account? ";

const home = "Home",
    categories = "Categories",
    cart = "Cart",
    account = "Account";

const search = "Search anything",
    todaydeal = "Today's Deal",
    flashsale = "Flash s\Sale",
    topseller = "Top Seller",
    brands = "Brands",
    topcat = "Top Catogeries",
    featcat = " Featured Categories",
    womendrs = "WomenDress",
    girlwatch = "Girls watchs",
    mobfon = "Mobile Phones",
    boysglas = "Boys Glasses",
    girlsdrs = "Girls Dresses",
    featuredprod = "Featured Prodect",
    automob = "Auto Mobile",
    kidstoy = "Kids & Toys",
    sports = "Sports",
    jwellry = "Jwelery",
    cellfon = "Cell Phone & Tab",
    furniture = "Furniture",
    compu = "Computer & accessories",
    mencloth = "Men Clothing & Fashion",
    video = "Video",
    reviews = "Reviews",
    sellerpolicy = "Selller Policy",
    returnpolicy = "Return Policy",
    supportpolicy = "Support Policy",
    productsyoulike = "Prodect you may like",
    tshirt = "T-Shirts";
