name: DreaMart
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  cloud_firestore: ^4.17.2
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  firebase_storage: ^11.7.4
  flutter:
    sdk: flutter
  get: ^4.6.6
  getx_screen: ^1.0.0
  image_picker: ^1.1.1
  velocity_x: ^4.1.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - lib/services/category_model.json
  #   - assets/
  # fonts:
  #   - family: sans_regular
  #     fonts:
  #       - assets/fonts/sans_regular.ttf
  #   - family: sans_bold
  #     fonts:
  #       - assets/fonts/sans_bold.ttf
  #   - family: sans_semibold
  #     fonts:
  #       - assets/fonts/sans_semibold.ttf
